### ISSUE TITLE
How to create an  ‘two dimensional array’ instance with ref-array?

### ISSUE THREAD

**Issue by PanYuntao** [TooTallNate/ref-array#2]
Hi~  create an array instance with the length automatically determined like this:

var buf = new Buffer(int.size \* 3)
int.set(buf, int.size \* 0, 5)
int.set(buf, int.size \* 1, 8)
int.set(buf, int.size \* 2, 0)
var array = IntArray.untilZeros(buf)

How to create an  ‘two dimensional array’ instance with ref-array?

**Comment by CodeFalling** [comment]
Did you find an answer on this question?Or how to create an ‘array of array’?

**Comment by ztooner** [comment]
Isn't that just an array of pointers? I.E. the "outer" array just contains pointers to the individual "inner" arrays?
`const PtrArray = ArrayType('pointer');`
`const arrayPtr = new PtrArray(3);`
`arrayPtr[0] = [1, 2, 3, 4, 5, 6];`
...and so on.
